---
- name: INSTALL ON MINIKUBE UBUNTU
  hosts: ubuntu
  become: yes
  #SETUP MODULE 
  gather_facts: yes

  tasks:
    - name: Show IP
      debug:
        msg: "Your host is {{ ansible_host }} IP {{ ansible_all_ipv4_addresses }}" 
  # Install minikube
    - name: Install minikube
      shell: 
        "curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \ && chmod +x minikube "
  #iNSTALL MINIKUBE
    - name: Zainstaluj minikube
      shell: install minikube-linux-amd64 /usr/local/bin/minikube
      
    - name: Start minikube
      shell:  minikube start --driver=docker
      
    - name: Show minikube status
      shell: minikube status

