---
- name: INSTALL ON MINIKUBE UBUNTU
  hosts: ubuntu
  become: no
  #SETUP MODULE 
  gather_facts: yes

  tasks:
    - name: Show IP
      debug:
        msg: "Your host is {{ ansible_host }} IP {{ ansible_all_ipv4_addresses }}"
      
    - name: Start minikube
      shell:  minikube start --driver=docker
      
    - name: Show minikube status
      shell: minikube status

